### ISSUE TITLE
New gcloud pubsub ruby gem with 4MB limit fix

### ISSUE THREAD

**Issue by rdsubhas** [mia-0032/fluent-plugin-gcloud-pubsub-custom#39]
- References https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1513
- Once that is merged and a new gem is released, the message size could be bumped up again to `9.8mb`. Not sure if that's required at this point, but just opening an issue to keep track

**Comment by mia-0032** [comment]
@rdsubhas Thank you for your reporting.

Commented to https://github.com/mia-0032/fluent-plugin-gcloud-pubsub-custom/pull/37#issuecomment-301302263, I added `max_message_size` configuration param ( https://github.com/mia-0032/fluent-plugin-gcloud-pubsub-custom/pull/38 ).
It limits bytesize of one message.

I think Pub/Sub limits bytesize of **all** messages per once to 10MB on publishing and gRPC limits bytesize of **one** messages to 4MB on pulling.

Decreasing `max_total_size` to 4MB works fine, but it causes number of publishing messages increase.
Because of it, I decided to add new configuration and revert `max_total_size` to 9.8MB.
The latest version of the plugin seems to satisfy the limitations.

Does any problem happen when you use the latest version?

**Comment by quartzmo** [comment]
GoogleCloudPlatform/google-cloud-ruby#1513 has been merged. I'm not exactly sure when we will release the new version of [google-cloud-pubsub](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-pubsub), but I'm hoping to do so this week.

**Comment by mia-0032** [comment]
I updated google-cloud-pubsub gem to v0.26.0 including above PR.
So I close this issue. If the same error occurs, please reopen this issue.
